name: compression-59k-metal
channels:
  - defaults
dependencies:
  - ca-certificates=2024.3.11
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.13
  - pip=24.0
  - python=3.9.19
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - compressai==1.1.3
      - contourpy==1.2.1
      - cycler==0.12.1
      - easydict==1.10
      - filelock==3.14.0
      - fonttools==4.51.0
      - fsspec==2024.5.0
      - idna==3.7
      - importlib-resources==6.4.0
      - jinja2==3.1.4
      - jsonpatch==1.33
      - jsonpointer==2.4
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - mpmath==1.3.0
      - networkx==3.2.1
      - ninja==1.11.1
      - numpy==1.22.0
      - packaging==24.0
      - pillow==9.0.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytorch-msssim==1.0.0
      - pyzmq==26.0.3
      - requests==2.32.2
      - scipy==1.11.4
      - six==1.16.0
      - sympy==1.12
      - torch==2.3.0
      - torchfile==0.1.0
      - torchnet==0.0.4
      - torchvision==0.18.0
      - tornado==6.4
      - typing-extensions==4.11.0
      - urllib3==2.2.1
      - visdom==0.1.8.9
      - websocket-client==1.8.0
      - zipp==3.18.2
